name: Python Static Analysis

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  job:
    runs-on: ubuntu-latest

    steps:

    # https://github.com/actions/setup-python
    - name: Install Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.2'

    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install black==23.3.0 
        pip install flake8 
        pip install isort

    # https://github.com/actions/checkout
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run isort
      run: isort --check .

    - name: Run black
      run: black --check .

    - name: Run flake8
      run: flake8